version: '3.8'
services:
  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/web_ISD
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: web_ISD
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
